version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: